// GENERATED by scripts/generate-app-manifest.mts — do not hand-edit.
// Regenerate with `npm run copilot:manifest`; CI verifies with `npm run copilot:manifest:check`.

export const APP_MANIFEST_VERSION = 2;
export type AppDestination = { route: string; title: string; phrases: string[]; examples: string[]; access: "public" | "auth" | "signed-in"; navigationKind: "none" | "static" | "record" };

export const APP_DESTINATIONS: AppDestination[] = [
  {"route":"/","title":"Welcome","phrases":["landing page","public demo"],"examples":["Describe Voni","Show the public demo","How do I sign in?"],"access":"public","navigationKind":"none"},
  {"route":"/agents","title":"Agents","phrases":["agents","phone agents","agent library","my agents"],"examples":["Show my agents","Find an agent named Sara","Open the agent library"],"access":"signed-in","navigationKind":"static"},
  {"route":"/agents/[id]","title":"Agent details","phrases":["agent details","open agent"],"examples":["Find an agent named Sara","Open the second matching agent","Read this agent configuration"],"access":"signed-in","navigationKind":"record"},
  {"route":"/agents/new","title":"New agent","phrases":["new agent","create agent","build an agent","agent builder","agent wizard"],"examples":["Create a new agent","Read this wizard step","Go to review"],"access":"signed-in","navigationKind":"static"},
  {"route":"/calls/[id]","title":"Call details","phrases":["call details","open call"],"examples":["Find calls for Alex","Open the first matching call","Read this call summary"],"access":"signed-in","navigationKind":"record"},
  {"route":"/campaigns","title":"Campaigns","phrases":["campaigns","my campaigns"],"examples":["Open campaigns","Find my viewing campaign","Show active campaigns"],"access":"signed-in","navigationKind":"static"},
  {"route":"/campaigns/[id]","title":"Campaign details","phrases":["campaign details","open campaign"],"examples":["Find a campaign named Viewings","Read this campaign queue","Show the CSV upload control"],"access":"signed-in","navigationKind":"record"},
  {"route":"/campaigns/new","title":"New campaign","phrases":["new campaign","create campaign","start a campaign"],"examples":["Create a campaign","Read the campaign fields","Set campaign name to Viewings"],"access":"signed-in","navigationKind":"static"},
  {"route":"/dashboard","title":"Dashboard","phrases":["dashboard","home","overview"],"examples":["Open dashboard","Show the overview","Read recent calls"],"access":"signed-in","navigationKind":"static"},
  {"route":"/jobs","title":"Background jobs","phrases":["jobs","background jobs","job status"],"examples":["Open background jobs","Show failed jobs","Read job status"],"access":"signed-in","navigationKind":"static"},
  {"route":"/leads","title":"Leads","phrases":["leads","my leads","lead list"],"examples":["Open leads","Find a lead named Alex","Read the lead list"],"access":"signed-in","navigationKind":"static"},
  {"route":"/leads/[id]","title":"Lead details","phrases":["lead details","open lead"],"examples":["Find a lead named Alex","Open the second matching lead","Read this lead status"],"access":"signed-in","navigationKind":"record"},
  {"route":"/login","title":"Sign in","phrases":["login","sign in"],"examples":["Sign in to Voni","Continue with Google","Open sign in"],"access":"auth","navigationKind":"none"},
  {"route":"/numbers","title":"Phone numbers","phrases":["phone numbers","numbers","calling numbers","my numbers"],"examples":["Show phone numbers","Read the number assignments","Show available number actions"],"access":"signed-in","navigationKind":"static"},
  {"route":"/settings","title":"Settings","phrases":["settings","voice copilot","voice control","voice settings","preferences"],"examples":["Open settings","Open the Voice copilot tab","Set voice to Ivy"],"access":"signed-in","navigationKind":"static"},
  {"route":"/signup","title":"Sign up","phrases":["signup","sign up"],"examples":["Create my account","Sign up with Google","Join Voni"],"access":"auth","navigationKind":"none"},
];

/** Static routes voice may navigate to. Dynamic detail pages stay model-proposed, never invented. */
export const NAVIGABLE_ROUTES: string[] = ["/agents", "/agents/new", "/campaigns", "/campaigns/new", "/dashboard", "/jobs", "/leads", "/numbers", "/settings"];

export const SETTINGS_TABS_MANIFEST: Array<{ value: string; label: string; adminOnly: boolean }> = [
  { value: "account", label: "Account", adminOnly: false },
  { value: "voice", label: "Voice copilot", adminOnly: false },
  { value: "workspace", label: "Workspace", adminOnly: false },
  { value: "services", label: "Services", adminOnly: false },
  { value: "appearance", label: "Appearance", adminOnly: false },
  { value: "platform", label: "Platform", adminOnly: true },
];

/** Vocabulary boosts so recognition hears feature names the first time. */
export const APP_FEATURE_TERMS: string[] = ["Voni", "Voice copilot", "dashboard", "agent", "agents", "campaign", "campaigns", "lead", "leads", "phone numbers", "background jobs", "settings", "workspace", "services", "appearance"];
